version: '3.9'
services:
    node:
        build:
            context: .
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 2048M
        environment:
            PORT: 3000
            JWT_SECRET: secret
            JWT_EXPIRATION_TIME: 100
            JWT_REFRESH_TOKEN_SECRET: token_secret
            JWT_REFRESH_TOKEN_EXPIRATION_TIME: 100
            DATABASE_URL: postgres://user:password@db/db
        ports:
            - "3001:3000"
        volumes:
            - ./backend:/var/www/backend
            - ./docker-entrypoint.sh:/var/www/backend/docker-entrypoint.sh
        command: ["/bin/bash", "docker-entrypoint.sh"]
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_DB: db
            POSTGRES_PASSWORD: password
            POSTGRES_PORT: 5432
        ports:
            - "5432:5432"

